"""
archivist changelog general

Generate a general-purpose CHANGELOG-{date}.md for any project type.
No project-specific sections — just clean git diff output and blank fields
for you to fill in.

Invoked by either:
    archivist changelog
    archivist changelog general

Scopes automatically to the current git repo (or submodule) root.
Output is written to ARCHIVE/. Iterative command runs will preserve
user content and descriptions in the existing changelog, if present.
"""

import argparse
from pathlib import Path

from archivist.commands.changelog.changelog_base import ChangelogContext, run_changelog
from archivist.utils import (
    format_file_list,
    get_project_name,
    get_today,
    render_field,
)


def _get_extra_paths(git_root: Path) -> list[Path]:
    return [
        git_root / ".github",
        git_root / "README.md",
    ]


def _build_frontmatter(ctx: ChangelogContext) -> str:
    today = get_today()
    auto = {
        "class": "archive",
        "category": ["changelog"],
        "log-scope": "general",
        "modified": today,
        "UUID": ctx.changelog_uuid,
        "commit-sha": ctx.args.commit_sha or "",
        "files-modified": len(ctx.modified),
        "files-created": len(ctx.changes["A"]),
        "files-archived": len(ctx.true_deleted),
        "tags": [get_project_name(ctx.git_root)],
    }
    lines = ["---"]
    for key, value in auto.items():
        lines.extend(render_field(key, value))
    lines.append("---")
    return "\n".join(lines)


def _build_body(ctx: ChangelogContext) -> str:
    today = get_today()
    user_block = ctx.user_content if ctx.user_content is not None else """
## Notes


---

*This changelog was automatically generated by Archivist CLI.*
*See [Archivist CLI](https://github.com/lvnacy-notes/archivist-cli) for more information.*

"""

    return f"""

# Changelog — {today}

## Overview

| Field | Value |
|-------|-------|
| Date | {today} |
| Commit SHA | {ctx.args.commit_sha or "[fill in after commit]"} |
| Files Added | {len(ctx.changes["A"])} |
| Files Modified | {len(ctx.modified)} |
| Files Archived | {len(ctx.true_deleted)} |

## Changes

### Files Modified
{format_file_list(ctx.modified, "No files modified", ctx.descriptions, ctx.renames)}
### New Files Created
{format_file_list(ctx.changes["A"], "No new files", ctx.descriptions)}
### Files Removed / Archived
{format_file_list(ctx.true_deleted, "No files archived", ctx.descriptions)}

<!-- archivist:auto-end -->{user_block}"""


def run(args: argparse.Namespace) -> None:
    run_changelog(
        args,
        module_type="general",
        build_frontmatter=_build_frontmatter,
        build_body=_build_body,
        get_extra_paths=_get_extra_paths,
    )